### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by ango1994** [RafGarLo/202210-week4-day4-rafael-garcia#6]
Buenas Rafa! 

- No sé cómo lo has hecho, pero has instalado versiones más antigüas de algunas dependencias que entraban en conflicto. Cambialas por estas, borra node_modules y el package-lock y haz npm i. Debería solucionarse el problema. 

***
"@testing-library/jest-dom": "^5.16.5",
        "@testing-library/react": "^13.4.0",
        "@testing-library/user-event": "^13.5.0",
        "@types/jest": "^27.5.2",
        "@types/node": "^16.18.0",
        "@types/react": "^18.0.23",
        "@types/react-dom": "^18.0.7",
        "@typescript-eslint/eslint-plugin": "^5.41.0",
        "@typescript-eslint/parser": "^5.41.0",
        "eslint-config-prettier": "^8.5.0",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router-dom": "^6.4.2",
        "react-scripts": "^5.0.1",
        "typescript": "^4.8.4",
        "web-vitals": "^2.1.4"
***

En cuanto al código, ibas por el buen camino.

- Te ha faltado darle un estado incicial a tus robots en el contexto. Si es un array vacío no podremos pintar nada. Echale un ojo a esa forma de importación, ya que si no te entraría en conflicto con ru robots del useState. 
![image](https://user-images.githubusercontent.com/81623139/198570545-d009809c-cb21-4ce4-8e1b-b9e0ad14e888.png)
- En cuanto al provider, ahora mismo solo está envolviendo a un <p>, por lo tanto la información del contexto no es accesible para tu aplicación. Llevate el provider a tu fichero index, y envuelve el componente App con él. 
![image](https://user-images.githubusercontent.com/81623139/198570909-ce688a50-004a-45a1-90ff-4177ec2a4f4b.png)

Ánimo y a partir de ahora vamos a darle caña a los test. Si avanzamos menos en el challenge pero hemos hecho tests no pasa nada.

**Comment by RafGarLo** [comment]
Buenas. Pude conseguir ver los robots. Me devolvia un array vacio y quedó corregido. Esto lo se porque me lleve los archivos a un nuevo proyecto en el que arranqué react de nuevo, con lo que está ahora desnvinculado a github y netlify, pero al menos he podido ver el trabajo que hice. me estoy quedando atras con los tests y otras cuantas cosas.
